version: '3'



services:


        mysql-development:
                image: mysql:8.0.17
                environment:
                        MYSQL_ROOT_PASSWORD: securepassword
                        MYSQL_DATABASE: imsdb
                ports:
                    - "3308:3308"
        phpmyadmin:
               image: phpmyadmin/phpmyadmin
               container_name: phpmyadminsuite
               volumes:
                       - /sessions
               ports:
                       - 8090:80
               environment:
                       - PMA_ARBITRARY=1
               depends_on:
                       - mysql-development 
                

