version: '3'
services:
    datadelivery:
        build: .
        depends_on:
            - influxdb-development
            - mysql-development
        links:
                - "influxdb-development"
                - "mysql-development"
        command: node datadelivery.js
        ports:
            - "8090:8090"

    influxdb-development:
        container_name: my_influxdb
        image: influxdb
        environment:
                INFLUXDB_ADMIN_USER: secureuser
                INFLUXDB_ADMIN_PASSWORD: securepassword
        restart: always
        ports:
            - "8086:8086"
        volumes:
                - influxdb-volume:/var/lib/influxdb
    mysql-development:
        container_name: mariadb
        image: mariadb
        environment:
                MYSQL_USER: secureuser
                MYSQL_PASSWORD: securepassword
                MYSQL_ROOT_PASSWORD: securepassword
                MYSQL_DATABASE: imsdb
        ports:
            - "3308:3306"  
        volumes:
                - mysqldb-volume:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadminsuite
        volumes:
                - /sessions
        ports:
                - 8091:80
        environment:
                - PMA_ARBITRARY=1
        depends_on:
                - mysql-development        
volumes:
    influxdb-volume:
    mysqldb-volume:
   
    
            

